import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { asyncUserFetch } from '../src/redux/actions/users/userActions';
import { INIT_STATE } from '../src/redux/reducer/usersReducer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const users: any = useSelector<any>(
    (state) => state.users as typeof INIT_STATE
  );

  useEffect(() => {
    dispatch(asyncUserFetch());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Star Wars Characters</h1>
        {users?.loading && <div>Loading...</div>}
        <ul>
          {users.data.length > 0 &&
            users.data.map((user: any, idx: number) => (
              <li key={idx} className={styles.list_item}>
                {`Name -- ${user.name}`}
              </li>
            ))}
        </ul>
      </main>

      <footer className={styles.footer}>Next x Redux</footer>
    </div>
  );
};

export default Home;
